version: '3'

services:

    mysql:
        image: mysql:5.7
        container_name: mysql2
        command: --innodb-use-native-aio=0
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - desafio-nodejs-nginx-network

    node:
        build:
            context: ./node
            dockerfile: Dockerfile.node
        image: taiane94sb/full-cycle-rocks-docker-node
        container_name: node
        networks:
            - desafio-nodejs-nginx-network
        depends_on:
            - mysql
        volumes:
            - ./node:/usr/src/app
            - /usr/src/app/node_modules

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.nginx
        image: taiane94sb/full-cycle-rocks-docker-nginx
        container_name: nginx
        networks:
            - desafio-nodejs-nginx-network
        ports:
            - "8080:80"
        depends_on:
            - node

networks:
    desafio-nodejs-nginx-network:
        driver: bridge
